### ISSUE TITLE
Cannot set property 'ParentTimingId' of undefined

### ISSUE THREAD

**Issue by ilyabreev** [MiniProfiler/dotnet#200]
```
includes.js?v=4.0.0.0:161 Uncaught TypeError: Cannot set property 'ParentTimingId' of undefined
    at processJson (includes.js?v=4.0.0.0:161)
    at renderTemplate (includes.js?v=4.0.0.0:243)
    at buttonShow (includes.js?v=4.0.0.0:254)
    at Object.success (includes.js?v=4.0.0.0:143)
    at c (includes.js?v=4.0.0.0:1027)
    at Object.fireWith [as resolveWith] (includes.js?v=4.0.0.0:1027)
    at k (includes.js?v=4.0.0.0:1029)
    at XMLHttpRequest.r (includes.js?v=4.0.0.0:1029)
```
So miniprofiler is not showing.

Appears in ASP.NET Core MVC.
NuGet package 4.0.0-alpha6-79.

**Comment by gjsduarte** [comment]
While the bug isn't fixed I can suggest you disable the CamelCasePropertyNamesContractResolver.

**Comment by NickCraver** [comment]
@ilyabreev Is it possible you're setting global properties somewhere with Newtonsoft? For example: `JsonConvert.DefaultSettings`?

**Comment by NickCraver** [comment]
I pushed a set of changes to MyGet that should resolve the above, *if that is indeed the problem*. Leaving this open until we confirm that's the cause.

**Comment by ilyabreev** [comment]
Seems like it is indeed the problem. Can't reproduce on clean asp.net core project.

**Comment by chadwackerman** [comment]
I'm hitting this in 4.0.0-alpha8-165. Paste this at the top of ConfigureServices and uncomment the line to trigger it.

```
JsonConvert.DefaultSettings = (() =>
{
    var settings = new JsonSerializerSettings();
    // settings.ContractResolver = new CamelCasePropertyNamesContractResolver();
    return settings;
});
```

**Comment by sepehr1014** [comment]
We're having this problem on alpha 9 & we can't globally disable CamelCasePropertyNamesContractResolver. Hasn't this been fixed?

**Comment by rlenders** [comment]
Please reopen this issue. It's not fixed, reproducible in the latest version (4.0.0-alpha9-00215).
