### ISSUE TITLE
Bad rendering of the data-position attribute on script tag

### ISSUE THREAD

**Issue by SamuelGuine** [MiniProfiler/dotnet#540]
Hello,

With Mini Profiler 4.2.1 the attribute data-position on script tag has 2 double quote ending:  **data-position="Left""**

On EDGE : HTML1423 warning on console.

The script tag render :

`<script async id="mini-profiler" src="/mini-profiler-resources/includes.min.js?v=4.2.1+b27bea37e9" data-version="4.2.1+b27bea37e9" data-path="/mini-profiler-resources/" data-current-id="03f0b54a-0032-4e3b-9a44-24c25344505c" data-ids="03f0b54a-0032-4e3b-9a44-24c25344505c" data-position="Left"" data-scheme="Light" data-authorized="true" data-max-traces="15" data-toggle-shortcut="Alt+P" data-trivial-milliseconds="2.0" data-ignored-duplicate-execute-types="Open,OpenAsync,Close,CloseAsync"></script>`

My config:

```
<PackageReference Include="MiniProfiler.AspNetCore.Mvc" Version="4.2.1" />
<PackageReference Include="MiniProfiler.EntityFrameworkCore" Version="4.2.1" />
```

services.AddMiniProfiler().AddEntityFramework();

and 

`<mini-profiler />`

Best Regards

**Comment by dotnetshadow** [comment]
I'm seeing the same issue.

This has the unintended issue causing other problems with packages such as WebMarkupMin
https://github.com/Taritsyn/WebMarkupMin/issues/112

**Comment by mm98** [comment]
I can confirm, that this breaks HTML minification by WebMarkupMin

**Comment by NickCraver** [comment]
This was fixed already, but was not promoted to the NuGet feed yet. Look for 4.2.22 landing on NuGet in just a bit, or available on MyGet already!

**Comment by dotnetshadow** [comment]
@NickCraver cheers thanks for that

**Comment by SamuelGuine** [comment]
Yes, fixed !

**Comment by NickCraver** [comment]
Thanks for the confirmations!

**Comment by Sebastian-Marten** [comment]
Not sure if I'm doing something wrong here Nick, but I still have the issue after updating to 4.2.22 via NuGet.

**Comment by NickCraver** [comment]
What do your package references look like? Are you explicitly referencing an older MiniProfiler.Shared separately perhaps? That's where the fix was (shared between both ASP.NET and ASP.NET Core downstream).

**Comment by Sebastian-Marten** [comment]
I checked through every project and possible reference and couldn't find anything; I'm just using the NuGet packages in one project. Targeting .Net Framework 4.8.
I cleaned and reinstalled the packages and still have the same outcome. There must be something somewhere, I can see in the source that this shouldn't happen. I'll keep looking, it's not a big deal.
Thanks for the suggestion.

**Comment by dirkjonker** [comment]
I am experiencing this issue on a brand new ASP.NET project, 4.2.22 via NuGet, no odd references or other versions of MiniProfiler.Shared around. Getting the prerelease 4.2.51 version from MyGet doesn't seem to solve the issue either.
